In [1]:
import mujoco
import numpy as np

In [3]:
model = mujoco.MjModel.from_xml_path("agility_cassie/cassie.xml")
data = mujoco.MjData(model)

In [4]:
model.neq

4

In [5]:
model.eq_type

array([0, 0, 0, 0], dtype=int32)

In [7]:
mujoco.mjtEq.mjEQ_CONNECT

<mjtEq.mjEQ_CONNECT: 0>

In [8]:
# So looks like Cassie has all connect constraints.

In [9]:
data.efc_type

array([], dtype=int32)

In [10]:
mujoco.mj_forward(model, data)

In [12]:
data.efc_type

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3], dtype=int32)

In [13]:
mujoco.mjtConstraint.mjCNSTR_EQUALITY

<mjtConstraint.mjCNSTR_EQUALITY: 0>

In [15]:
mujoco.mjtConstraint.mjCNSTR_FRICTION_DOF

<mjtConstraint.mjCNSTR_FRICTION_DOF: 1>

In [17]:
data.efc_type == mujoco.mjtConstraint.mjCNSTR_EQUALITY

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False])

In [22]:
np.argwhere(data.efc_type == mujoco.mjtConstraint.mjCNSTR_EQUALITY).ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
data.efc_type == mujoco.mjtConstraint.mjCNSTR_EQUALITY

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False])

In [18]:
data.efc_J.shape

(512,)

In [20]:
data.efc_J.reshape((data.nefc, model.nv)).shape

(16, 32)